<?php

if(sfConfig::has('app_rt_site_visitor_credential'))
{
  $cred = sfConfig::get('app_rt_site_visitor_credential') . "\n";
}

?>

<?php if(sfConfig::get('app_rt_site_is_private', false)): ?>
all:
  is_secure: true
  <?php if (isset($cred)): ?>
  credentials: <?php echo $cred ?>
  <?php endif; ?>
<?php endif; ?>

create:
  is_secure: true
  credentials: admin_site